config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

from posts.views import list

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', list, name='home'),  # 메인 페이지 지정

    path('accounts/', include('accounts.urls')),  # accounts 앱의 urls 사용
    path('posts/', include('posts.urls')),  # posts 앱의 urls 사용
    path('scraps/', include('scraps.urls')),
    path('photolog/', include('photolog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path

from posts.views import list, detail, create, update, delete, comment_create, scrap  # new

app_name = 'posts'

urlpatterns = [
    path('<int:id>/scrap/', scrap, name='scrap'),
    path('<int:id>/comment/create/', comment_create, name='comment_create'),
    path('<int:id>/update/', update, name='update'),
    path('<int:id>/delete/', delete, name='delete'),
    path('<int:id>/', detail, name='detail'),
    path('', list, name='list'),
    # path('new/', new, name='new'),
    path('create/', create, name='create'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User 

class Post(models.Model):
    """ 게시글 모델 """
    title = models.CharField(
        verbose_name='제목',
        max_length=80,
    )

    content = models.TextField(
        verbose_name='내용'
    )

    created_at = models.DateTimeField(
        verbose_name='작성일'
    )

    created_by = models.CharField(
        verbose_name='작성자',
        max_length=100
    )

    is_view = models.BooleanField(
        verbose_name='공개 여부',
        default=True
    )

class Comment(models.Model):
    """ 댓글 모델 """
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE)


class Scrap(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE)

posts/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect

from .models import Post, Comment, Scrap

@login_required  # 로그인한 경우에만 허용
def scrap(request, id):
    post = get_object_or_404(Post, id=id)
    scrap_filter = Scrap.objects.filter(user=request.user, post=post)
    if len(scrap_filter) < 1:
        Scrap.objects.create(user=request.user, post=post)
    else:
        scrap_filter.delete()

    url = request.META.get('HTTP_REFERER', '/')
    return redirect(url)
    

def comment_create(request, id):
    post = get_object_or_404(Post, id=id)
    content = request.POST.get('content')
    Comment.objects.create(content=content, post=post)
    return redirect('posts:detail', post.id)

def delete(request, id):  # url 패턴의 /delete/<int:id>/ 의 id 값으로 데이터베이스 조회
    """ 게시글 삭제 View """
    context = {}
    post = Post.objects.get(id=id)  # Post 모델으 id 필드가 id인 데이터 조회
    if request.method == 'POST':
        post.delete()  # POST 요청인 경우 데이터 삭제
        return redirect('posts:list')  # url name list url로 리다이렉트 응답
    else:
        context.update(post=post)  # 10 줄에서 생성한 context 변수에 post 키로 post 값 업데이트
        return render(request, 'posts/confirm_delete.html', context)

def update(request, id):  # url 패턴의 /update/<int:id>/ 의 id 값으로 데이터베이스 조회
    context = {'title':'글 수정', 'submit_text': '수정하기'}  # form.html 사용 시 제목과 제출 버튼 이름 지정
    post = Post.objects.get(id=id)  # Post 모델으 id 필드가 id인 데이터 조회
    if request.method == 'POST':
        title = request.POST['title']  # form > input name이 title 값 가져오기
        content = request.POST['content']  # form > input name이 content 값 가져오기
        created_by = request.POST['created_by']  # form > input name이 created_by 값 가져오기
        
        post.title = title  # 21 줄에서 조회한 객체의 title 값 변경
        post.content = content  # 21 줄에서 조회한 객체의 content 값 변경
        post.created_by = created_by  # 21 줄에서 조회한 객체의 created_by 값 변경
        post.save()  # 데이터베이스에 반영(저장)
        return redirect('posts:detail', id)  # url 패턴 detial에 id값을 넣어 리다이렉트
    else:
        context.update(post=post)  # form에 기존 값 추가를 위해 21에서 조회한 Post 인스턴스 context에 업데이트
        return render(request, 'posts/form.html', context)
        
        

def list(request):
    post_all = Post.objects.all()  # Post 모델의 전체 데이터 조회 
    context = {'post_all': post_all}  # 응답의 context 데이터 생성
    return render(request, 'posts/list.html', context)  # 요청에 응답 함수, 'list.html'은 파일명이며 templates 폴더에 존재해야 함

def detail(request, id):
    post = Post.objects.get(id=id)  # Post 모델의 특정 데이터 조회
    comment_list = Comment.objects.filter(post=post)  # Comment 모델의 post필드가 위에서 조회한 post인 것 조회
    if not request.user.is_anonymous:
        scrap = Scrap.objects.filter(user=request.user, post=post)
    else:
        scrap = None
    context = {'post': post, 'comment_list': comment_list, 'scrap': scrap}
    return render(request, 'posts/detail.html', context)

# def new(request):
#         context = {'title':'글 등록', 'submit_text': '등록하기'}
#         return render(request, 'form.html', context)
    
def create(request):
    if request.method == 'POST':
        now = datetime.now()  # 현재 시간을 구하기 위한 함수
        title = request.POST['title']  # 클라이언트에서 POST 요청으로 넘어온 form의 name=title인 값을 title 변수에 할당
        content = request.POST['content']  # 클라이언트에서 POST 요청으로 넘어온 form의 name=content인 값을 content 변수에 할당
        created_by = request.POST['created_by']  # 클라이언트에서 POST 요청으로 넘어온 form의 name=created_by인 값을 created_by 변수에 할당
        post = Post.objects.create(
            title=title,  # Post 모델 title 필드에 title 변수 값 입력
            content=content,  # Post 모델 content 필드에 content 변수 값 입력
            created_by=created_by,  # Post 모델 created_by 필드에 created_by 변수 값 입력
            created_at=now,  # Post 모델 created_at 필드에 now 변수 값 입력
        )
        return redirect('home')
    else:
        context = {'title':'글 등록', 'submit_text': '등록하기'}
        return render(request, 'posts/form.html', context)

templates/posts/confirm_delete.html
{% extends 'base.html' %}

{% block title %}글 삭제{% endblock %}

{% block content %}
<h1>글 삭제</h1>
<form action="" method="POST">
    {% csrf_token %}
    {% include 'mixins/post_card.html' %}
    <div>
        <p>위 글을 삭제하시겠습니까?</p>
        <p>삭제된 글은 복원할 수 없습니다.</p>
    </div>
    <input type="submit" value="삭제하기">
    <a href="{{ request.META.HTTP_REFERER }}">뒤로가기</a>
</form>
{% endblock %}

templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}글 상세{% endblock %}

{% block content %}
<h1>글 상세페이지</h1>
{% include 'mixins/post_card.html' %}
<a href="{% url 'posts:list' %}">목록보기</a>
<a href="{% url 'posts:update' post.id %}">수정하기</a>
<a href="{% url 'posts:delete' post.id %}">삭제하기</a>
<a href="{% url 'posts:scrap' post.id %}">
    {% if scrap %}
    스크랩 취소
    {% else %}
    스크랩
    {% endif %}
</a>
{{scrap}}
<hr>
<form action="{% url 'posts:comment_create' post.id %}" method="POST">
    {% csrf_token %}
    <input type="text" name="content">
    <input type="submit" value="댓글 작성하기">
</form>

{% for comment in comment_list %} {# view context로 전달 받은 변수 #}
<p>{{ comment.content }} | {{ comment.created_at }}</p>
{% empty %} {# 반복 데이터가 없는 경우 출력 #}
<p>댓글이 없습니다.</p>
{% endfor %}
{% endblock %}

templates/posts/form.html
{% extends 'base.html' %}

{% block title %}{{title}}{% endblock %}

{% block content %}
    <h1>{{ title }}</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <div>
            <label for="">제목</label>
            <input type="text" name="title" value="{{ post.title }}">
        </div>
        <div>
            <label for="">내용</label>
            <textarea name="content">{{ post.content }}</textarea>
        </div>
        <div>
            <label for="">작성자</label>
            <input type="text" name="created_by" value="{{ post.created_by }}">
        </div>
        <input type="submit" value="{{ submit_text }}">
        <a href="{{ request.META.HTTP_REFERER }}">뒤로가기</a>
        <a href="{% url 'posts:list' %}">목록으로</a>
    </form>
{% endblock %}

templates/posts/list.html
{% extends 'base.html' %}

{% block title %}글 목록 {% endblock %}

{% block content %}
<h1>글 목록 페이지</h1>
<div><a href="{% url 'posts:create' %}">글쓰기</a></div>
<table border="1">
    <tr>
        <th>번호</th>
        <th>제목</th>
        <th>작성자</th>
        <th>작성일</th>
    </tr>
    {% for post in post_all %}
    <tr>
        <td>{{ post.id }}</td>
        <td><a href="{% url 'posts:detail' post.id %}">{{ post.title }}</a></td>
        <td>{{ post.created_by }}</td>
        <td>{{ post.created_at }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}