config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

from posts.views import list

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', list, name='home'),  # 메인 페이지 지정

    path('accounts/', include('accounts.urls')),  # accounts 앱의 urls 사용
    path('posts/', include('posts.urls')),  # posts 앱의 urls 사용
    path('scraps/', include('scraps.urls')),
    path('photolog/', include('photolog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

photolog/urls.py
from django.urls import path

from .views import list, create

app_name = 'photolog'

urlpatterns = [
	path('', list, name='list'),
	path('create/', create, name='create'),
]

posts/urls.py
from django.urls import path

from posts.views import list, detail, create, update, delete, comment_create, scrap  # new

app_name = 'posts'

urlpatterns = [
    path('<int:id>/scrap/', scrap, name='scrap'),
    path('<int:id>/comment/create/', comment_create, name='comment_create'),
    path('<int:id>/update/', update, name='update'),
    path('<int:id>/delete/', delete, name='delete'),
    path('<int:id>/', detail, name='detail'),
    path('', list, name='list'),
    # path('new/', new, name='new'),
    path('create/', create, name='create'),
]

photolog/models.py
from django.db import models

class Photolog(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/')
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.title

photolog/views.py
from django.shortcuts import render, redirect

from .models import Photolog

def list(request):
    photolog = Photolog.objects.all()
    return render(request, 'photolog/list.html', {'photolog': photolog})

def create(request):
    if request.method == 'POST':
        title = request.POST['title']
        image = None
        if 'image' in request.FILES:
            image = request.FILES['image']
        description = request.POST['description']
        
        photolog = Photolog(title=title, image=image, description=description)
        photolog.save()
        return redirect('photolog:list')
    else:
        return render(request, 'photolog/form.html')

templates/photolog/form.html
{% extends 'base.html' %}
{% load static %}
{% block title %}이미지{% endblock %}

{% block content %}
<h1>이미지 업로드</h1>

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="">제목</label>
    <input type="text" name="title" placeholder="사진 제목"><br>
    <label for="">이미지</label>
    <input type="file" name="image"><br>
    <label for="">내용</label>
    <input type="text" name="description" placeholder="글"><br>
    <input type="submit" value="글쓰기"><br>
</form>
{% endblock %}

templates/photolog/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}이미지{% endblock %}

{% block content %}
<h1>이미지</h1>
<div></div>

<a href="{% url 'photolog:create' %}">이미지 업로드</a>
<div>
{% for photolog in photolog.all %}
    {{ photolog.title }}<br>
    {% if photolog.image %}
    <img src="{{ photolog.image.url }}"><br>
    {% endif %}
    {{ photolog.description }}<br>
{% endfor %}
</div>
{% endblock %}