accounts/urls.py
from django.urls import path
from .views import signup, login, logout  # 요청을 넘길 함수 불러오기

app_name = 'accounts'  # 템플릿 url 태그 사용 시 네임스페이스 지정

urlpatterns = [
		path('signup/', signup, name='signup'),  # accounts/signup/ url 요청 시 signup 함수로 전달
		path('login/', login, name='login'),  # accounts/login/ url 요청 시 login 함수로 전달
		path('logout/', logout, name='logout'),  # accounts/logout/ url 요청 시 logout 함수로 전달
]

config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

from posts.views import list

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', list, name='home'),  # 메인 페이지 지정

    path('accounts/', include('accounts.urls')),  # accounts 앱의 urls 사용
    path('posts/', include('posts.urls')),  # posts 앱의 urls 사용
    path('scraps/', include('scraps.urls')),
    path('photolog/', include('photolog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

photolog/urls.py
from django.urls import path

from .views import list, create

app_name = 'photolog'

urlpatterns = [
	path('', list, name='list'),
	path('create/', create, name='create'),
]

posts/urls.py
from django.urls import path

from posts.views import list, detail, create, update, delete, comment_create, scrap  # new

app_name = 'posts'

urlpatterns = [
    path('<int:id>/scrap/', scrap, name='scrap'),
    path('<int:id>/comment/create/', comment_create, name='comment_create'),
    path('<int:id>/update/', update, name='update'),
    path('<int:id>/delete/', delete, name='delete'),
    path('<int:id>/', detail, name='detail'),
    path('', list, name='list'),
    # path('new/', new, name='new'),
    path('create/', create, name='create'),
]

scraps/urls.py
from django.urls import path
from .views import list

app_name = 'scraps'

urlpatterns = [
	path('', list, name='list'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <title>{% block title %}{% endblock %} | 1멋직</title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>
    <header>
        <img src="{% static 'likelion.png' %}" alt="logo" class="logo">
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">홈</a></li>
                <li><a href="{% url 'posts:list' %}">게시판</a></li>
                <li><a href="{% url 'photolog:list' %}">이미지</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'scraps:list' %}">스크랩 보기</a></li>
                    <li><a href="{% url 'accounts:logout' %}">로그아웃</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:login' %}">로그인</a></li>
                    <li><a href="{% url 'accounts:signup' %}">회원가입</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
{% block content %}{% endblock%}

{% block javascript %}{% endblock %}
</body>
</html>